language: erlang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - build-essential

notifications:
  email: you@example.org
otp_release:
  - 18.2
  - 18.1
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.1
  - 17.0
  - R16B03
script:
  - make test
