language: erlang
notifications:
  email: you@example.org
otp_release:
  - 18.2
  - 18.1
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.1
  - 17.0
  - R16B03
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02
  - R14B01
script:
  - make test
